"""Shared deck I/O for the tools. Not runnable on its own.

Both audio.py and images.py load the same two files and write the same
attribution list, so that lives here rather than drifting between them.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTES_PATH = ROOT / "deck/notes.json"
MANIFEST_PATH = ROOT / "media/manifest.json"
ATTRIB_PATH = ROOT / "media/ATTRIBUTION.md"

KEY_ORDER = ["id", "word", "gloss", "pos", "ipa", "note", "image", "image_alt",
             "image_prompt", "audio", "sentence", "cards", "reviewed"]
SENT_KEY_ORDER = ["pl", "en", "gap", "answer", "answer_lemma", "audio"]

# Everything the project puts where Windows can open it goes under one root.
OUT_ROOT = "flashcards"


def out_dir(sub):
    for d in sorted(Path("/mnt/c/Users").glob("*/Downloads")):
        if d.is_dir() and not d.parent.name.startswith(("Default", "All Users", "Public")):
            return d / OUT_ROOT / sub
    return ROOT / ".out" / sub          # gitignored fallback when not on WSL


def load_key(name):
    """Read one key out of .env. Never printed, never committed."""
    env = ROOT / ".env"
    if not env.exists():
        raise SystemExit(f"no .env — expected {name} in {env}")
    for line in env.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith(f"{name}="):
            v = line.split("=", 1)[1].strip().strip("'\"")
            if v:
                return v
    raise SystemExit(f".env has no {name} value")


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def reorder(d, order):
    return {k: d[k] for k in order if k in d} | {k: v for k, v in d.items() if k not in order}


def load():
    deck = json.loads(NOTES_PATH.read_text(encoding="utf-8"))
    manifest = (json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
                if MANIFEST_PATH.exists() else {})
    return deck, deck["notes"], manifest


def save(deck, notes, manifest):
    deck["notes"] = [
        reorder({**n, **({"sentence": reorder(n["sentence"], SENT_KEY_ORDER)}
                         if isinstance(n.get("sentence"), dict) else {})}, KEY_ORDER)
        for n in notes]
    NOTES_PATH.write_text(json.dumps(deck, ensure_ascii=False, indent=2) + "\n",
                          encoding="utf-8")
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, ensure_ascii=False, indent=2,
                                        sort_keys=True) + "\n", encoding="utf-8")
    write_attribution(manifest)


def write_attribution(manifest):
    """Reused media carries licence obligations; meet them from the manifest."""
    rows = [(rel, v) for rel, v in sorted(manifest.items())
            if v.get("source") in ("commons", "openverse", "wikipedia")]
    if not rows:
        ATTRIB_PATH.unlink(missing_ok=True)
        return
    lines = ["# Media attribution", "",
             "Reused under the licences below. Generated by the tools in `tools/` —",
             "do not edit by hand.", "",
             "| File | Title | Author | Licence | Source |", "| --- | --- | --- | --- | --- |"]
    for rel, v in rows:
        page = v.get("page") or v.get("source_url") or ""
        title = v.get("commons_file") or v.get("title") or ""
        link = f"[{title}]({page})" if page else title
        lines.append(f"| `{rel}` | {link} | {v.get('author', 'unknown')} "
                     f"| {v.get('licence', 'unknown')} | {v.get('source')} |")
    ATTRIB_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
